### ISSUE TITLE
Loadouts manuell aufrufbar

### ISSUE THREAD

**Issue by felixlinker** [felixlinker/W_Missionstemplate#13]
Loadouts sollten per Funktion noch während des Spiels aufrufbar sein.

**Comment by GitHawk** [comment]
Sind sie doch. Spontan würde ich mal folgendes probieren:
GLOBAL EXEC `if (name player == "xyz") then {call FETT_framework_fnc_applyLoadout};`

**Comment by felixlinker** [comment]
Stimmt, ist aber nicht schön, weil die Loadouts dann bei jedem Aufruf neu kompiliert werden.

**Comment by GitHawk** [comment]
Es sollte nicht so häufig vorkommen und bei jedem JIP muss es eh neu kompiliert werden.
Du könntest allerhöchstens den Code `compile preprocessFileLineNumbers _file` zwischenspeichern, aber das würde dann halt RAM kosten.

**Comment by felixlinker** [comment]
Es gibt Missionsbauer, die KI mit eigenen Loadouts ausstatten wollen.
An die soll sich das richten.
Am 09.02.2016 09:55 schrieb "Hawk" <notifications@github.com>:

**Comment by GitHawk** [comment]
Dann funktioniert `FETT_framework_fnc_applyLoadout` aber grundsätzlich nicht, da darin `player` hardcoded verwendet wird. 
Es müsste zumindest optional ein `_obj` übergeben werden, dem das Loadout hinzugefügt wird.
Ebenso könnte man einen `if (isServer || isHC) then { _useLoadoutCaching = true };` einbauen.

**Comment by GitHawk** [comment]
Mal n Vorschlag #14 zum Thema

**Comment by GitHawk** [comment]
Geht nun sowohl über `[_unit, _loadout, _side] call FETT_framework_fnc_applyLoadout;` als auch über `[_unit, _loadout] call FETT_fnc_X_loadout;`

**Comment by felixlinker** [comment]
Ich werde bei den Wrappern noch eine kleine Sache ändern, sodass der Aufruf konsistent für den Missionsbauer bleibt, dann close ich den hier. Die sind es gewohnt, dass sie per *[_obj,_loadout]* Aufrufen.

**Comment by GitHawk** [comment]
Ich hab im "alten" extra nachgeschaut - da stand:
`private _fnc = format ["FETT_fnc_%1_loadout",["b","i","c","o"] select ([west,independent,civilian,east] find side player)];
_fnc = missionNamespace getVariable _fnc;
[(player getVariable ["loadout",""]),player] call _fnc;`

**Comment by felixlinker** [comment]
Stimmt, hast recht. Bin doof.
