### ISSUE TITLE
Loadouts crashen

### ISSUE THREAD

**Issue by felixlinker** [felixlinker/W_Missionstemplate#15]
Die Loadouts crashen im Moment, weil der Aufruf durch das Framework mit Parametern erfolgt. Parameter sind `["client","postinit"]`.

Entweder bauen wir den Aufruf des Loadoutskripts um, oder es werden einfach die Parameter entfernt, die eh noch nicht verwendet werden.

**Comment by GitHawk** [comment]
Brauchen andere Scripte die Parameter? Wenn nein einfach rauswerfen.

`FETT_vd_fnc_add` verwendet ebenfalls `params`

**Comment by GitHawk** [comment]
Sieht nicht so aus aktuell - zumindest bei den clientInit Funktionen.

**Comment by felixlinker** [comment]
Nein, ich verwende die nicht weiter. Ich dachte mir nur, dass das eventuell zum Debuggen oder loggen interessant sein könnte. Aber ich werde sie wohl entfernen, hast recht.

**Comment by GitHawk** [comment]
Kannst ja noch einen Rest für Logging/Debugging da lassen.
Optimal wäre, wenn in den CfgFramework.hpp ebenfalls beschrieben wird, welche Parameter übergeben werden (müssen)

**Comment by felixlinker** [comment]
Du kannst in der CfgFramework Parameter übergeben, indem du `code = "args call function";` machst. Und genau so werde ich das auch für die Loadouts fixen, ich Idiot!
